# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.15.2' # [Required] Define the Elixir version
        otp-version: '26.0'      # [Required] Define the Erlang/OTP version
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
            - name: Setup .NET Core SDK
  uses: actions/setup-dotnet@v4.0.0
  with:
    # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
    dotnet-version: # optional
    # Optional quality of the build. The possible values are: daily, signed, validated, preview, ga.
    dotnet-quality: # optional
    # Optional global.json location, if your global.json isn't located in the root of the repo.
    global-json-file: # optional
    # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword
    source-url: # optional
    # Optional OWNER for using packages from GitHub Package Registry organizations/users other than the current repository's owner. Only used if a GPR URL is also provided in source-url
    owner: # optional
    # Optional NuGet.config location, if your NuGet.config isn't located in the root of the repo.
    config-file: # optional
    # Optional input to enable caching of the NuGet global-packages folder
    cache: # optional
    # Used to specify the path to a dependency file: packages.lock.json. Supports wildcards or a list of file names for caching multiple dependencies.
    cache-dependency-path: # optional
                      - name: Create Artifact YAML
  # You may pin to the exact commit or the version.
  # uses: opencontextinc/create-artifact-yaml@218aadb9180fd982c8f2aaa592573297bdb9550e
  uses: opencontextinc/create-artifact-yaml@v1.0.1
  with:
    # Type of artifact. One of sbom, container, package, or image
    type: 
    # URL/URI of the artifact
    url: 
    # Directory to save YAML files to. If not specified then the directory oc-artifact-yaml will be used.
    directory: # optional
                      - name: Create NuGet Package for Octopus Deploy
  # You may pin to the exact commit or the version.
  # uses: OctopusDeploy/create-nuget-package-action@64e3cec8f57c50b3e7cdfabd006e4d1a24b94f4d
  uses: OctopusDeploy/create-nuget-package-action@v3.0.2
  with:
    # Package Id.
    package_id: 
    # Package version.
    version: 
    # The folder to put the resulting package in, relative to the current working directory; not the base path.
    output_folder: 
    # The base path for the input files.
    base_path: 
    # Multi-line list of files to include in the package. Supports globbing.
    files: 
    # Description to include in the Nuspec file. 
    nuspec_description: 
    # Multi-line list of authors to include in the Nuspec file.
    nuspec_authors: 
    # Release notes to include in the Nuspec file.
    nuspec_release_notes: # optional
          
            - name: Azure PowerShell Action
  uses: Azure/powershell@v2
  with:
    # Specify the Az PowerShell script here.
    inlineScript: 
    # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
    azPSVersion: 
    # Select the value of the ErrorActionPreference variable for executing the script. Options: stop, continue, silentlyContinue. Default is Stop.
    errorActionPreference: # optional, default is Stop
    # If this is true, this task will fail if any errors are written to the error pipeline, or if any data is written to the Standard Error stream.
    failOnStandardError: # optional, default is false
    # Used to pull Az module from Azure/az-ps-module-versions.  Since there's a default, this is typically not supplied by the user.
    githubToken: # optional, default is ${{ github.token }}

                      - name: Install powershell
  # You may pin to the exact commit or the version.
  # uses: cakhanif/action-install-powershell@9287716f19f5547fb975cd59dc23b286fabffdf8
  uses: cakhanif/action-install-powershell@v1
                      - name: Install powershell-devops Module
  # You may pin to the exact commit or the version.
  # uses: powershell-devops/powershell-devops@02eb25c9e71d654cf5e82f4af4b09cd7ba31054e
  uses: powershell-devops/powershell-devops@v0.2.0
  with:
    # Optional required version to install. If not provided, will install the latest version. Example: 0.0.7
    required-version: # optional
    # Optional minimum version to install. If not provided, will install the latest version. Example: 0.0.7
    minimum-version: # optional
    # Optional maximum version to install. If not provided, will install the latest version. Example: 0.0.7
    maximum-version: # optional
                      - name: PowerShell virtual environment
  # You may pin to the exact commit or the version.
  # uses: Tyler887/PS-Runner@fef5dec7a99030c203e89faee47f358fa09c3a99
  uses: Tyler887/PS-Runner@1.4.1

                      - name: Benchmark with Benchpress
  # You may pin to the exact commit or the version.
  # uses: StartAutomating/Benchpress@5dc858c3c350c9f9d4fa8d6cc3aa35810a741fe9
  uses: StartAutomating/Benchpress@v1.3.6
  with:
    # The path to the benchmark file.  
If not provided, any benchmark files in your repository will be used

    BenchmarkPath: # optional
    # The path to the module.
    ModulePath: # optional
    # The output path for the benchmark files.  By default "docs"
    OutputPath: # optional, default is docs
    # If provided, will commit any remaining changes made to the workspace with this commit message.
If no commit message is provided, changes will not be committed.

    CommitMessage: # optional
    # The user email associated with a git commit.
    UserEmail: # optional
    # The user name associated with a git commit.
    UserName: # optional

                      - name: Azure Login
  uses: Azure/login@v2.0.0
  with:
    # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
    creds: # optional
    # ClientId of the Azure Service principal created.
    client-id: # optional
    # TenantId of the Azure Service principal created.
    tenant-id: # optional
    # Azure subscriptionId
    subscription-id: # optional
    # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
    enable-AzPSSession: # optional
    # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
    environment: # optional, default is azurecloud
    # Set this value to true to enable support for accessing tenants without subscriptions
    allow-no-subscriptions: # optional
    # Provide audience field for access-token. Default value is api://AzureADTokenExchange
    audience: # optional, default is api://AzureADTokenExchange
    # The type of authentication. Supported values are SERVICE_PRINCIPAL, IDENTITY. Default value is SERVICE_PRINCIPAL
    auth-type: # optional, default is SERVICE_PRINCIPAL

            - name: PnP PowerShell with OIDC
  # You may pin to the exact commit or the version.
  # uses: anoopt/action-pnp-powershell-with-oidc@a17e2d45f2e151383c3fb9d46ea79d782b08ed24
  uses: anoopt/action-pnp-powershell-with-oidc@v1.3.0
  with:
    # ID of the tenant
    TENANT_ID: 
    # Name of the tenant
    TENANT_NAME: 
    # ID of the AAD application registration
    CLIENT_ID: 
    # URL of the site to connect to
    SITE_URL: 
    # The audience for the federated token (default is api://AzureADTokenExchange)
    AUDIENCE: # optional
    # The PnP PowerShell script to execute after connecting
    PNP_POWERSHELL_SCRIPT: # optional
          
          
